<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="WINDOWS-R8SKFHD" failures="1" tests="1" name="Validating Assertions" time="178.71" errors="0" timestamp="24 Mar 2022 08:38:49 GMT">
  <testcase classname="cucmberOptions.TestRunner" name="feature" time="176.093">
    <failure type="cucumber.runtime.CucumberException" message="java.lang.AssertionError: expected [Account already exists with this mobile number. Please login.] but found [Invalid mobile number.]">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: expected [Account already exists with this mobile number. Please login.] but found [Invalid mobile number.]
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
Caused by: java.lang.AssertionError: expected [Account already exists with this mobile number. Please login.] but found [Invalid mobile number.]
	at stepDefinations.stepDefination.verify_that_user_is_successfully_logged_in(stepDefination.java:97)
	at âœ½.Then Verify that user is successfully logged in(src/test/java/features/Login.feature:8)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- feature -->
</testsuite> <!-- Validating Assertions -->
